### PR TITLE
Fix marshalling of verificationMethod

### LINKED ISSUE #33: New VerificationMethod does not equals unmarshalled form
```golang
method, _ := NewVerificationMethod(*id123Method, ssi.JsonWebKey2020, *id123, pair.PublicKey)
methodJson, _ := json.Marshal(method)
unmarshalledMethod := &VerificationMethod{}
json.Unmarshal(methodJson, unmarshalledMethod)
assert.Equal(t, method, unmarshalledMethod)
```
Fails

### PR DESCRIPTION
**Pull request by stevenvegt**
Fix #33

### CODE REVIEW

File: did/document.go [hunk 1]
```diff
@@ -280,7 +280,12 @@ func NewVerificationMethod(id DID, keyType ssi.KeyType, controller DID, key cryp
 		if err != nil {
 			return nil, err
 		}
-		vm.PublicKeyJwk = jwkAsMap
+		// go to JSON and back to fix encoding of key material
```
Comment (reinkrul) [inline did/document.go:283]: can we mention why we need this and `jwkAsMap` isn't sufficient?

**Review by reinkrul — CHANGES_REQUESTED** [review]

File: did/document.go (hunk 1 above)
Comment (woutslakhorst) [reply did/document.go]: so it removes lib specific types.

**Review by woutslakhorst — APPROVED** [review]
